import { Shield } from 'lucide-react'

export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto animate-fade-in">
      {/* Header */}
      <div className="mb-10">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-500/20 flex items-center justify-center">
            <Shield size={20} className="text-indigo-400" />
          </div>
          <span className="text-xs font-semibold uppercase tracking-widest text-indigo-400">Legal</span>
        </div>
        <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
        <p className="text-slate-400 text-sm">Last updated: June 19, 2026</p>
      </div>

      {/* Content */}
      <div className="prose-legal">
        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
          of Your information when You use the Service and tells You about Your privacy rights and how
          the law protects You. We use Your Personal Data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2>Interpretation and Definitions</h2>
        <h3>Interpretation</h3>
        <p>
          The words whose initial letters are capitalized have meanings defined under the following
          conditions. The following definitions shall have the same meaning regardless of whether they
          appear in singular or in plural.
        </p>

        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Application</strong> refers to MathVerse AI, the software program provided by the Company.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to <a href="https://mathverseai.org">https://mathverseai.org</a>.</li>
          <li><strong>Cookies</strong> are small files placed on Your computer, mobile device or any other device by a website, containing details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Haryana, India.</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Application or the Website or both.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          <li><strong>Website</strong> refers to <a href="https://mathverseai.org" target="_blank" rel="noreferrer">https://mathverseai.org</a>.</li>
          <li><strong>You</strong> means the individual accessing or using the Service.</li>
        </ul>

        <h2>Collecting and Using Your Personal Data</h2>
        <h3>Types of Data Collected</h3>
        <h4>Personal Data</h4>
        <p>While using Our Service, We may ask You to provide certain personally identifiable information, including but not limited to:</p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
        </ul>

        <h4>Usage Data</h4>
        <p>
          Usage Data is collected automatically when using the Service. It may include Your Device's
          Internet Protocol address, browser type and version, the pages You visit, the time and date
          of Your visit, time spent on pages, unique device identifiers, and other diagnostic data.
        </p>

        <h4>Tracking Technologies and Cookies</h4>
        <p>
          We use Cookies and similar tracking technologies to track activity on Our Service and store
          certain information. We use both Session and Persistent Cookies for the purposes below:
        </p>
        <ul>
          <li><strong>Necessary / Essential Cookies</strong> — Session Cookies administered by Us to authenticate users and prevent fraudulent use.</li>
          <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> — Persistent Cookies to identify if users have accepted the use of cookies.</li>
          <li><strong>Functionality Cookies</strong> — Persistent Cookies to remember choices such as login details or language preference.</li>
        </ul>

        <h3>Use of Your Personal Data</h3>
        <p>The Company may use Personal Data to:</p>
        <ul>
          <li><strong>Provide and maintain our Service</strong>, including monitoring usage.</li>
          <li><strong>Manage Your Account</strong> and registration as a user.</li>
          <li><strong>Perform a contract</strong> — including purchase contracts for subscriptions.</li>
          <li><strong>Contact You</strong> regarding updates, security alerts, and informative communications.</li>
          <li><strong>Provide You</strong> with news, special offers, and information about similar goods and services.</li>
          <li><strong>Manage Your requests</strong> to Us.</li>
          <li><strong>Business transfers</strong> — evaluate mergers, acquisitions or asset sales.</li>
          <li><strong>Other purposes</strong> such as data analysis, usage trends, and improving our Service.</li>
        </ul>

        <h3>Retention of Your Personal Data</h3>
        <p>
          The Company will retain Your Personal Data only for as long as necessary for the purposes set
          out in this Privacy Policy. Retention periods:
        </p>
        <ul>
          <li><strong>User Accounts</strong> — retained for the duration of your account plus up to 24 months after closure.</li>
          <li><strong>Support tickets</strong> — up to 24 months from ticket closure.</li>
          <li><strong>Usage Data / analytics</strong> — up to 24 months from date of collection.</li>
          <li><strong>Server logs</strong> — up to 24 months for security monitoring.</li>
        </ul>

        <h3>Transfer of Your Personal Data</h3>
        <p>
          Your information may be transferred to and maintained on computers located outside Your
          jurisdiction where data protection laws may differ. We will take all steps reasonably
          necessary to ensure Your data is treated securely and in accordance with this Privacy Policy.
        </p>

        <h3>Delete Your Personal Data</h3>
        <p>
          You have the right to delete or request that We assist in deleting the Personal Data We have
          collected about You. You may do so by signing into Your Account settings or by contacting Us.
        </p>

        <h3>Disclosure of Your Personal Data</h3>
        <h4>Business Transactions</h4>
        <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before this occurs.</p>

        <h4>Law enforcement</h4>
        <p>The Company may disclose Your Personal Data if required by law or in response to valid requests by public authorities.</p>

        <h4>Other legal requirements</h4>
        <p>The Company may disclose Your Personal Data to comply with a legal obligation, protect rights or property, prevent wrongdoing, or protect against legal liability.</p>

        <h3>Security of Your Personal Data</h3>
        <p>
          The security of Your Personal Data is important to Us. While We strive to use commercially
          reasonable means to protect Your data, no method of transmission over the Internet is 100%
          secure.
        </p>

        <h2>Children's Privacy</h2>
        <p>
          Our Service does not address anyone under the age of 16. We do not knowingly collect
          personally identifiable information from anyone under 16. If You are a parent or guardian
          and Your child has provided Us with Personal Data, please contact Us immediately.
        </p>

        <h2>Links to Other Websites</h2>
        <p>
          Our Service may contain links to other websites not operated by Us. We have no control over
          and assume no responsibility for the content or privacy policies of any third-party sites.
        </p>

        <h2>Changes to this Privacy Policy</h2>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by
          posting the new Privacy Policy on this page and updating the "Last updated" date.
        </p>

        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, contact us:</p>
        <ul>
          <li>By email: <a href="mailto:shilpy.tandon@gmail.com">shilpy.tandon@gmail.com</a></li>
          <li>Website: <a href="https://mathverseai.org">mathverseai.org</a></li>
        </ul>
      </div>
    </div>
  )
}
